apiVersion: security.kubedig.com/v1
kind: KubeDigClusterPolicy
metadata:
  annotations:
    app.accuknox.com/source: KubeDig Operator
    app.accuknox.com/type: harden
  name: harden-system-owner-discovery
spec:
  action: Block
  message: System owner discovery command execution denied
  process:
    matchPaths:
      - path: /usr/bin/who
      - path: /usr/bin/w
      - path: /usr/bin/id
      - path: /usr/bin/whoami
  selector:
    matchExpressions:
  severity: 3
  tags:
  - MITRE
  - MITRE_T1082_system_information_discovery

