// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Authors of KubeDig

// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	"fmt"

	v1 "github.com/zfz-725/KubeDig/pkg/KubeDigController/api/security.kubedig.com/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=security.kubedig.com, Version=v1
	case v1.SchemeGroupVersion.WithResource("kubedigclusterpolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Security().V1().KubeDigClusterPolicies().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("kubedighostpolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Security().V1().KubeDigHostPolicies().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("kubedigpolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Security().V1().KubeDigPolicies().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
