// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Authors of KubeDig

// Code generated by lister-gen. DO NOT EDIT.

package v1

// KubeDigClusterPolicyListerExpansion allows custom methods to be added to
// KubeDigClusterPolicyLister.
type KubeDigClusterPolicyListerExpansion interface{}

// KubeDigHostPolicyListerExpansion allows custom methods to be added to
// KubeDigHostPolicyLister.
type KubeDigHostPolicyListerExpansion interface{}

// KubeDigPolicyListerExpansion allows custom methods to be added to
// KubeDigPolicyLister.
type KubeDigPolicyListerExpansion interface{}

// KubeDigPolicyNamespaceListerExpansion allows custom methods to be added to
// KubeDigPolicyNamespaceLister.
type KubeDigPolicyNamespaceListerExpansion interface{}
