// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Authors of KubeDig

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/zfz-725/KubeDig/pkg/KubeDigController/api/security.kubedig.com/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// KubeDigHostPolicyLister helps list KubeDigHostPolicies.
// All objects returned here must be treated as read-only.
type KubeDigHostPolicyLister interface {
	// List lists all KubeDigHostPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.KubeDigHostPolicy, err error)
	// Get retrieves the KubeDigHostPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.KubeDigHostPolicy, error)
	KubeDigHostPolicyListerExpansion
}

// kubeDigHostPolicyLister implements the KubeDigHostPolicyLister interface.
type kubeDigHostPolicyLister struct {
	indexer cache.Indexer
}

// NewKubeDigHostPolicyLister returns a new KubeDigHostPolicyLister.
func NewKubeDigHostPolicyLister(indexer cache.Indexer) KubeDigHostPolicyLister {
	return &kubeDigHostPolicyLister{indexer: indexer}
}

// List lists all KubeDigHostPolicies in the indexer.
func (s *kubeDigHostPolicyLister) List(selector labels.Selector) (ret []*v1.KubeDigHostPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.KubeDigHostPolicy))
	})
	return ret, err
}

// Get retrieves the KubeDigHostPolicy from the index for a given name.
func (s *kubeDigHostPolicyLister) Get(name string) (*v1.KubeDigHostPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("kubedighostpolicy"), name)
	}
	return obj.(*v1.KubeDigHostPolicy), nil
}
