// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Authors of KubeDig

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/zfz-725/KubeDig/pkg/KubeDigController/api/security.kubedig.com/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// KubeDigClusterPolicyLister helps list KubeDigClusterPolicies.
// All objects returned here must be treated as read-only.
type KubeDigClusterPolicyLister interface {
	// List lists all KubeDigClusterPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.KubeDigClusterPolicy, err error)
	// Get retrieves the KubeDigClusterPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.KubeDigClusterPolicy, error)
	KubeDigClusterPolicyListerExpansion
}

// kubeDigClusterPolicyLister implements the KubeDigClusterPolicyLister interface.
type kubeDigClusterPolicyLister struct {
	indexer cache.Indexer
}

// NewKubeDigClusterPolicyLister returns a new KubeDigClusterPolicyLister.
func NewKubeDigClusterPolicyLister(indexer cache.Indexer) KubeDigClusterPolicyLister {
	return &kubeDigClusterPolicyLister{indexer: indexer}
}

// List lists all KubeDigClusterPolicies in the indexer.
func (s *kubeDigClusterPolicyLister) List(selector labels.Selector) (ret []*v1.KubeDigClusterPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.KubeDigClusterPolicy))
	})
	return ret, err
}

// Get retrieves the KubeDigClusterPolicy from the index for a given name.
func (s *kubeDigClusterPolicyLister) Get(name string) (*v1.KubeDigClusterPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("kubedigclusterpolicy"), name)
	}
	return obj.(*v1.KubeDigClusterPolicy), nil
}
