// SPDX-License-Identifier: Apache-2.0
// Copyright 2023 Authors of KubeDig

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/zfz-725/KubeDig/pkg/KubeDigOperator/api/operator.kubedig.com/v1"
	scheme "github.com/zfz-725/KubeDig/pkg/KubeDigOperator/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KubeDigConfigsGetter has a method to return a KubeDigConfigInterface.
// A group's client should implement this interface.
type KubeDigConfigsGetter interface {
	KubeDigConfigs(namespace string) KubeDigConfigInterface
}

// KubeDigConfigInterface has methods to work with KubeDigConfig resources.
type KubeDigConfigInterface interface {
	Create(ctx context.Context, kubeDigConfig *v1.KubeDigConfig, opts metav1.CreateOptions) (*v1.KubeDigConfig, error)
	Update(ctx context.Context, kubeDigConfig *v1.KubeDigConfig, opts metav1.UpdateOptions) (*v1.KubeDigConfig, error)
	UpdateStatus(ctx context.Context, kubeDigConfig *v1.KubeDigConfig, opts metav1.UpdateOptions) (*v1.KubeDigConfig, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.KubeDigConfig, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.KubeDigConfigList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.KubeDigConfig, err error)
	KubeDigConfigExpansion
}

// kubeDigConfigs implements KubeDigConfigInterface
type kubeDigConfigs struct {
	client rest.Interface
	ns     string
}

// newKubeDigConfigs returns a KubeDigConfigs
func newKubeDigConfigs(c *OperatorV1Client, namespace string) *kubeDigConfigs {
	return &kubeDigConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kubeDigConfig, and returns the corresponding kubeDigConfig object, and an error if there is any.
func (c *kubeDigConfigs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.KubeDigConfig, err error) {
	result = &v1.KubeDigConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kubedigconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KubeDigConfigs that match those selectors.
func (c *kubeDigConfigs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.KubeDigConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.KubeDigConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kubedigconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kubeDigConfigs.
func (c *kubeDigConfigs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kubedigconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kubeDigConfig and creates it.  Returns the server's representation of the kubeDigConfig, and an error, if there is any.
func (c *kubeDigConfigs) Create(ctx context.Context, kubeDigConfig *v1.KubeDigConfig, opts metav1.CreateOptions) (result *v1.KubeDigConfig, err error) {
	result = &v1.KubeDigConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kubedigconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kubeDigConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kubeDigConfig and updates it. Returns the server's representation of the kubeDigConfig, and an error, if there is any.
func (c *kubeDigConfigs) Update(ctx context.Context, kubeDigConfig *v1.KubeDigConfig, opts metav1.UpdateOptions) (result *v1.KubeDigConfig, err error) {
	result = &v1.KubeDigConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kubedigconfigs").
		Name(kubeDigConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kubeDigConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *kubeDigConfigs) UpdateStatus(ctx context.Context, kubeDigConfig *v1.KubeDigConfig, opts metav1.UpdateOptions) (result *v1.KubeDigConfig, err error) {
	result = &v1.KubeDigConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kubedigconfigs").
		Name(kubeDigConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kubeDigConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kubeDigConfig and deletes it. Returns an error if one occurs.
func (c *kubeDigConfigs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kubedigconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kubeDigConfigs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kubedigconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kubeDigConfig.
func (c *kubeDigConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.KubeDigConfig, err error) {
	result = &v1.KubeDigConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kubedigconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
