// SPDX-License-Identifier: Apache-2.0
// Copyright 2023 Authors of KubeDig

// Code generated by lister-gen. DO NOT EDIT.

package v1

// KubeDigConfigListerExpansion allows custom methods to be added to
// KubeDigConfigLister.
type KubeDigConfigListerExpansion interface{}

// KubeDigConfigNamespaceListerExpansion allows custom methods to be added to
// KubeDigConfigNamespaceLister.
type KubeDigConfigNamespaceListerExpansion interface{}
