// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Authors of KubeDig

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/zfz-725/KubeDig/pkg/KubeDigController/client/clientset/versioned/typed/security.kubedig.com/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSecurityV1 struct {
	*testing.Fake
}

func (c *FakeSecurityV1) KubeDigClusterPolicies() v1.KubeDigClusterPolicyInterface {
	return &FakeKubeDigClusterPolicies{c}
}

func (c *FakeSecurityV1) KubeDigHostPolicies() v1.KubeDigHostPolicyInterface {
	return &FakeKubeDigHostPolicies{c}
}

func (c *FakeSecurityV1) KubeDigPolicies(namespace string) v1.KubeDigPolicyInterface {
	return &FakeKubeDigPolicies{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSecurityV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
