// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Authors of KubeDig

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	securitykubedigcomv1 "github.com/zfz-725/KubeDig/pkg/KubeDigController/api/security.kubedig.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKubeDigHostPolicies implements KubeDigHostPolicyInterface
type FakeKubeDigHostPolicies struct {
	Fake *FakeSecurityV1
}

var kubedighostpoliciesResource = schema.GroupVersionResource{Group: "security.kubedig.com", Version: "v1", Resource: "kubedighostpolicies"}

var kubedighostpoliciesKind = schema.GroupVersionKind{Group: "security.kubedig.com", Version: "v1", Kind: "KubeDigHostPolicy"}

// Get takes name of the kubeDigHostPolicy, and returns the corresponding kubeDigHostPolicy object, and an error if there is any.
func (c *FakeKubeDigHostPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *securitykubedigcomv1.KubeDigHostPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(kubedighostpoliciesResource, name), &securitykubedigcomv1.KubeDigHostPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*securitykubedigcomv1.KubeDigHostPolicy), err
}

// List takes label and field selectors, and returns the list of KubeDigHostPolicies that match those selectors.
func (c *FakeKubeDigHostPolicies) List(ctx context.Context, opts v1.ListOptions) (result *securitykubedigcomv1.KubeDigHostPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(kubedighostpoliciesResource, kubedighostpoliciesKind, opts), &securitykubedigcomv1.KubeDigHostPolicyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &securitykubedigcomv1.KubeDigHostPolicyList{ListMeta: obj.(*securitykubedigcomv1.KubeDigHostPolicyList).ListMeta}
	for _, item := range obj.(*securitykubedigcomv1.KubeDigHostPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kubeDigHostPolicies.
func (c *FakeKubeDigHostPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(kubedighostpoliciesResource, opts))
}

// Create takes the representation of a kubeDigHostPolicy and creates it.  Returns the server's representation of the kubeDigHostPolicy, and an error, if there is any.
func (c *FakeKubeDigHostPolicies) Create(ctx context.Context, kubeDigHostPolicy *securitykubedigcomv1.KubeDigHostPolicy, opts v1.CreateOptions) (result *securitykubedigcomv1.KubeDigHostPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(kubedighostpoliciesResource, kubeDigHostPolicy), &securitykubedigcomv1.KubeDigHostPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*securitykubedigcomv1.KubeDigHostPolicy), err
}

// Update takes the representation of a kubeDigHostPolicy and updates it. Returns the server's representation of the kubeDigHostPolicy, and an error, if there is any.
func (c *FakeKubeDigHostPolicies) Update(ctx context.Context, kubeDigHostPolicy *securitykubedigcomv1.KubeDigHostPolicy, opts v1.UpdateOptions) (result *securitykubedigcomv1.KubeDigHostPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(kubedighostpoliciesResource, kubeDigHostPolicy), &securitykubedigcomv1.KubeDigHostPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*securitykubedigcomv1.KubeDigHostPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKubeDigHostPolicies) UpdateStatus(ctx context.Context, kubeDigHostPolicy *securitykubedigcomv1.KubeDigHostPolicy, opts v1.UpdateOptions) (*securitykubedigcomv1.KubeDigHostPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(kubedighostpoliciesResource, "status", kubeDigHostPolicy), &securitykubedigcomv1.KubeDigHostPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*securitykubedigcomv1.KubeDigHostPolicy), err
}

// Delete takes name of the kubeDigHostPolicy and deletes it. Returns an error if one occurs.
func (c *FakeKubeDigHostPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(kubedighostpoliciesResource, name), &securitykubedigcomv1.KubeDigHostPolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKubeDigHostPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(kubedighostpoliciesResource, listOpts)

	_, err := c.Fake.Invokes(action, &securitykubedigcomv1.KubeDigHostPolicyList{})
	return err
}

// Patch applies the patch and returns the patched kubeDigHostPolicy.
func (c *FakeKubeDigHostPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *securitykubedigcomv1.KubeDigHostPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(kubedighostpoliciesResource, name, pt, data, subresources...), &securitykubedigcomv1.KubeDigHostPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*securitykubedigcomv1.KubeDigHostPolicy), err
}
