# kubedig-ca secret
{{- $ca := genCA "kubedig"  1095 -}}
{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.kubedig.tls.caSecretName }}
  labels:
    kubedig-app: {{ .Values.kubedig.tls.caSecretName }}
  namespace: {{.Release.Namespace}}
data:
  tls.key: {{ $ca.Key | b64enc }}
  tls.crt: {{ $ca.Cert | b64enc }}
{{- end}}
---
{{- if .Values.tls.enabled }}
{{- $altNames := list ( printf "kubedig.%s" .Release.Namespace ) ( printf "kubedig.%s.svc" .Release.Namespace ) ( printf "kubedig.%s.svc.cluster.local" .Release.Namespace ) -}}
{{- $dns := concat .Values.kubedigRelay.tls.extraDnsNames $altNames -}}
{{- $ip := .Values.kubedigRelay.tls.extraIpAddresses -}}
{{- $cert := genSignedCert "kubedig-relay" $ip $dns 1095 $ca -}}
# kubedig-relay-certs secret
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.kubedigRelay.tls.certSecretName }}
  labels:
    kubedig-app: {{ .Values.kubedigRelay.tls.certSecretName }}
  namespace: {{.Release.Namespace}}
data:
  tls.key: {{ $cert.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end}}
---
{{- if .Values.tls.enabled }}
{{- $cert := genSignedCert "kubedig-relay" nil nil 1095 $ca -}}
# kubedig-client-certs secret
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.kubedig.tls.clientCertSecretName }}
  labels:
    kubedig-app: {{ .Values.kubedig.tls.clientCertSecretName }}
  namespace: {{.Release.Namespace}}
data:
  tls.key: {{ $cert.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end}}