apiVersion: security.kubedig.com/v1
kind: KubeDigPolicy
metadata:
  name: ksp-wordpress-block-config
  namespace: wordpress-mysql
spec:
  severity: 10
  selector:
    matchLabels:
      app: wordpress
  file:
    matchPaths:
    - path: /var/www/html/wp-config.php
      fromSource:
      - path: /bin/cat

      # http://[NodeIP]:30080
      # cat /var/www/html/wp-config.php
 
  action:
    Block
