// SPDX-License-Identifier: Apache-2.0
// Copyright 2023 Authors of KubeDig

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/zfz-725/KubeDig/pkg/KubeDigOperator/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// KubeDigConfigs returns a KubeDigConfigInformer.
	KubeDigConfigs() KubeDigConfigInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// KubeDigConfigs returns a KubeDigConfigInformer.
func (v *version) KubeDigConfigs() KubeDigConfigInformer {
	return &kubeDigConfigInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
