#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2021 Authors of KubeDig

realpath() {
    CURR=$PWD

    cd "$(dirname "$0")"
    LINK=$(readlink "$(basename "$0")")

    while [ "$LINK" ]; do
        cd "$(dirname "$LINK")"
        LINK=$(readlink "$(basename "$1")")
    done

    REALPATH="$PWD/$(basename "$1")"
    echo "$REALPATH"
}

MOD_DIR=`dirname $(realpath "$0")`
cd $MOD_DIR

generate_requirements() {
    semanage fcontext -l | awk -F"object_r:" '{print $2}' | awk 'NF' | sort -u | awk -F':' '{print $1}' > kdig.tmp

    echo >> kdig.te
    echo "require {" >> kdig.te

    while read line; do
        echo "    type $line;" >> kdig.te
    done < kdig.tmp

    echo "}" >> kdig.te
}

generate_unconfined_service_rules() {
    semanage fcontext -l | awk -F"object_r:" '{print $2}' | awk 'NF' | sort -u | awk -F':' '{print $1}' > kdig.tmp

    echo >> kdig.te

    echo "require {" >> kdig.te
    echo "    type unconfined_service_t;" >> kdig.te
    echo "}" >> kdig.te

    echo >> kdig.te

    echo "allow unconfined_service_t unconfined_service_t:capability2 { mac_admin };" >> kdig.te

    echo >> kdig.te

    while read line; do
        echo "allow unconfined_service_t $line:file { getattr relabelfrom relabelto };" >> kdig.te
    done < kdig.tmp
}

generate_kdig_base() {
    # directory and files

    semanage fcontext -l | grep "all files" | awk -F"object_r:" '{print $2}' | awk 'NF' | sort -u | awk -F':' '{print $1}' > kdig.tmp

    echo > kdig.base

    while read line; do
        echo "allow_dir_access(kdig_t, $line)" >> kdig.base
        echo "allow_file_access(kdig_t, $line)" >> kdig.base
    done < kdig.tmp

    # directory

    semanage fcontext -l | grep "directory" | awk -F"object_r:" '{print $2}' | awk 'NF' | sort -u | awk -F':' '{print $1}' > kdig.tmp

    echo >> kdig.base

    while read line; do
        echo "allow_dir_access(kdig_t, $line)" >> kdig.base
        echo "allow_file_access(kdig_t, $line)" >> kdig.base
    done < kdig.tmp

    # files

    semanage fcontext -l | grep -v "all files" | grep -v "directory" | awk -F"object_r:" '{print $2}' | awk 'NF' | sort -u | awk -F':' '{print $1}' > kdig.tmp

    echo >> kdig.base

    while read line; do
        echo "allow_file_access(kdig_t, $line)" >> kdig.base
    done < kdig.tmp
}

generate_kdig_directory_base() {
    # directory and files

    semanage fcontext -l | grep "all files" | awk -F"object_r:" '{print $2}' | awk 'NF' | sort -u | awk -F':' '{print $1}' > kdig.tmp

    echo > kdig.dir

    while read line; do
        echo "allow_dir_access(kdig_t, $line)" >> kdig.dir
    done < kdig.tmp

    # directory

    semanage fcontext -l | grep "directory" | awk -F"object_r:" '{print $2}' | awk 'NF' | sort -u | awk -F':' '{print $1}' > kdig.tmp

    echo >> kdig.dir

    while read line; do
        echo "allow_dir_access(kdig_t, $line)" >> kdig.dir
    done < kdig.tmp
}

generate_kdig() {
    echo "# automatically generated (do not edit this file)" > kdig.te
    echo >> kdig.te
    echo "policy_module(kdig, 1.0.0)" >> kdig.te
    echo >> kdig.te

    echo "########################################" >> kdig.te

    cat default/common_macro >> kdig.te

    echo >> kdig.te
    echo "########################################" >> kdig.te

    cat default/common_template >> kdig.te

    echo >> kdig.te
    echo "########################################" >> kdig.te

    cat default/kdig_macro >> kdig.te

    echo >> kdig.te
    echo "########################################" >> kdig.te

    # generate required types
    generate_requirements

    # generate rules for unconfined_service_t
    generate_unconfined_service_rules

    # generate base file and directory rules
    generate_kdig_base

    # generate base directory rules
    generate_kdig_directory_base

    echo >> kdig.te
    echo "########################################" >> kdig.te

    cat default/kdig_global >> kdig.te

    echo >> kdig.tmp
    echo "########################################" >> kdig.tmp

    ## default posture ##

    for elem in {0..2} # 3 elements (block, audit, allow)
    do
        defaultPosture="block"

        if [[ $elem == 1 ]]; then
            defaultPosture="audit"
        elif [[ $elem == 2 ]]; then
            defaultPosture="allow"
        fi

        ## fromSource ##

        for code in {0..15} # 4 elements -> 2^4 (matchProtocols)
        do
            cat default/kdig_template > kdig.tmp

            TCP="n"
            UDP="n"
            ICMP="n"
            RAW="n"

            # tcp
            if (( (code & 0x1) == 0x1 )); then
                echo "allow_tcp_network_operation(kdig_t)" >> kdig.tmp
                TCP="t"
            fi

            # udp
            if (( (code & 0x2) == 0x2 )); then
                echo "allow_udp_network_operation(kdig_t)" >> kdig.tmp
                UDP="u"
            fi

            # icmp
            if (( (code & 0x4) == 0x4 )); then
                echo "allow_icmp_network_operation(kdig_t)" >> kdig.tmp
                echo "allow_raw_network_operation(kdig_t)" >> kdig.tmp
                ICMP="i"
            fi

            # raw
            if (( (code & 0x8) == 0x8 )); then
                if (( (code & 0x4) != 0x4 )); then
                    echo "allow_raw_network_operation(kdig_t)" >> kdig.tmp
                fi
                RAW="r"
            fi

            if [[ $defaultPosture != "block" ]]; then
                echo >> kdig.tmp
                echo "########################################" >> kdig.tmp

                cat kdig.base >> kdig.tmp
            else
                echo >> kdig.tmp
                echo "########################################" >> kdig.tmp

                cat kdig.dir >> kdig.tmp
            fi

            echo >> kdig.tmp
            echo "########################################" >> kdig.tmp

            sed "s/kdig\_/kdig\_$defaultPosture\_$TCP$UDP$ICMP$RAW\_/g" kdig.tmp >> kdig.te
        done

        ##

    done

    ##
}

compile_and_inject_selinux_module() {
    # clean up the previous module
    rm -rf kdig.fc kdig.if kdig.pp kdig.base kdig.dir kdig.tmp tmp

    # create files
    echo > kdig.fc
    echo > kdig.if

    # compile and insert selinux module
    make -f /usr/share/selinux/devel/Makefile kdig.pp && semodule -i kdig.pp
    if [ $? != 0 ]; then
        # remove temp files
        rm -rf kdig.fc kdig.if kdig.pp kdig.base kdig.dir kdig.tmp tmp

        echo "Failed to install $1 SELinux module"
        exit 1
    fi

    # remove temp files
    rm -rf kdig.fc kdig.if kdig.pp kdig.base kdig.dir kdig.tmp tmp
}

# step 1
generate_kdig

# step 2
compile_and_inject_selinux_module

exit 0
