apiVersion: security.kubedig.com/v1
kind: KubeDigHostPolicy
metadata:
  name: hsp-kubedig-dev-file-path-block-fromsource
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: kubedig-dev
  severity: 5
  file:
    matchPaths:
    - path: /etc/hostname
      fromSource:
      - path: /usr/bin/head
  action:
    Block

# kubedig-dev_test_06

# test
# $ head /etc/hostname
# head: cannot open '/etc/hostname' for reading: Permission denied
# $ head /etc/hosts
# ...

# expectation
# /usr/bin/head cannot access /etc/hostname
# /usr/bin/head can access any others
