apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedig-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubedig-clusterrole
subjects:
- kind: ServiceAccount
  name: kubedig
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedig-relay-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubedig-relay-clusterrole
subjects:
- kind: ServiceAccount
  name: kubedig-relay
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.kubedigController.name }}-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.kubedigController.name }}-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ .Values.kubedigController.name }}
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.kubedigController.name }}-leader-election-rolebinding
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.kubedigController.name }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.kubedigController.name }}
  namespace: {{ .Release.Namespace }}

