// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Authors of KubeDig

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/zfz-725/KubeDig/pkg/KubeDigController/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// KubeDigClusterPolicies returns a KubeDigClusterPolicyInformer.
	KubeDigClusterPolicies() KubeDigClusterPolicyInformer
	// KubeDigHostPolicies returns a KubeDigHostPolicyInformer.
	KubeDigHostPolicies() KubeDigHostPolicyInformer
	// KubeDigPolicies returns a KubeDigPolicyInformer.
	KubeDigPolicies() KubeDigPolicyInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// KubeDigClusterPolicies returns a KubeDigClusterPolicyInformer.
func (v *version) KubeDigClusterPolicies() KubeDigClusterPolicyInformer {
	return &kubeDigClusterPolicyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// KubeDigHostPolicies returns a KubeDigHostPolicyInformer.
func (v *version) KubeDigHostPolicies() KubeDigHostPolicyInformer {
	return &kubeDigHostPolicyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// KubeDigPolicies returns a KubeDigPolicyInformer.
func (v *version) KubeDigPolicies() KubeDigPolicyInformer {
	return &kubeDigPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
