// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Authors of KubeDig

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	securitykubedigcomv1 "github.com/zfz-725/KubeDig/pkg/KubeDigController/api/security.kubedig.com/v1"
	versioned "github.com/zfz-725/KubeDig/pkg/KubeDigController/client/clientset/versioned"
	internalinterfaces "github.com/zfz-725/KubeDig/pkg/KubeDigController/client/informers/externalversions/internalinterfaces"
	v1 "github.com/zfz-725/KubeDig/pkg/KubeDigController/client/listers/security.kubedig.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KubeDigHostPolicyInformer provides access to a shared informer and lister for
// KubeDigHostPolicies.
type KubeDigHostPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.KubeDigHostPolicyLister
}

type kubeDigHostPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewKubeDigHostPolicyInformer constructs a new informer for KubeDigHostPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKubeDigHostPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKubeDigHostPolicyInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredKubeDigHostPolicyInformer constructs a new informer for KubeDigHostPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKubeDigHostPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityV1().KubeDigHostPolicies().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityV1().KubeDigHostPolicies().Watch(context.TODO(), options)
			},
		},
		&securitykubedigcomv1.KubeDigHostPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *kubeDigHostPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKubeDigHostPolicyInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kubeDigHostPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&securitykubedigcomv1.KubeDigHostPolicy{}, f.defaultInformer)
}

func (f *kubeDigHostPolicyInformer) Lister() v1.KubeDigHostPolicyLister {
	return v1.NewKubeDigHostPolicyLister(f.Informer().GetIndexer())
}
