// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Authors of KubeDig

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	securitykubedigcomv1 "github.com/zfz-725/KubeDig/pkg/KubeDigController/api/security.kubedig.com/v1"
	versioned "github.com/zfz-725/KubeDig/pkg/KubeDigController/client/clientset/versioned"
	internalinterfaces "github.com/zfz-725/KubeDig/pkg/KubeDigController/client/informers/externalversions/internalinterfaces"
	v1 "github.com/zfz-725/KubeDig/pkg/KubeDigController/client/listers/security.kubedig.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KubeDigClusterPolicyInformer provides access to a shared informer and lister for
// KubeDigClusterPolicies.
type KubeDigClusterPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.KubeDigClusterPolicyLister
}

type kubeDigClusterPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewKubeDigClusterPolicyInformer constructs a new informer for KubeDigClusterPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKubeDigClusterPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKubeDigClusterPolicyInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredKubeDigClusterPolicyInformer constructs a new informer for KubeDigClusterPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKubeDigClusterPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityV1().KubeDigClusterPolicies().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityV1().KubeDigClusterPolicies().Watch(context.TODO(), options)
			},
		},
		&securitykubedigcomv1.KubeDigClusterPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *kubeDigClusterPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKubeDigClusterPolicyInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kubeDigClusterPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&securitykubedigcomv1.KubeDigClusterPolicy{}, f.defaultInformer)
}

func (f *kubeDigClusterPolicyInformer) Lister() v1.KubeDigClusterPolicyLister {
	return v1.NewKubeDigClusterPolicyLister(f.Informer().GetIndexer())
}
