// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Authors of KubeDig

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	securitykubedigcomv1 "github.com/zfz-725/KubeDig/pkg/KubeDigController/api/security.kubedig.com/v1"
	versioned "github.com/zfz-725/KubeDig/pkg/KubeDigController/client/clientset/versioned"
	internalinterfaces "github.com/zfz-725/KubeDig/pkg/KubeDigController/client/informers/externalversions/internalinterfaces"
	v1 "github.com/zfz-725/KubeDig/pkg/KubeDigController/client/listers/security.kubedig.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KubeDigPolicyInformer provides access to a shared informer and lister for
// KubeDigPolicies.
type KubeDigPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.KubeDigPolicyLister
}

type kubeDigPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKubeDigPolicyInformer constructs a new informer for KubeDigPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKubeDigPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKubeDigPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKubeDigPolicyInformer constructs a new informer for KubeDigPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKubeDigPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityV1().KubeDigPolicies(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecurityV1().KubeDigPolicies(namespace).Watch(context.TODO(), options)
			},
		},
		&securitykubedigcomv1.KubeDigPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *kubeDigPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKubeDigPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kubeDigPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&securitykubedigcomv1.KubeDigPolicy{}, f.defaultInformer)
}

func (f *kubeDigPolicyInformer) Lister() v1.KubeDigPolicyLister {
	return v1.NewKubeDigPolicyLister(f.Informer().GetIndexer())
}
