// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Authors of KubeDig

// Code generated by client-gen. DO NOT EDIT.

package v1

type KubeDigClusterPolicyExpansion interface{}

type KubeDigHostPolicyExpansion interface{}

type KubeDigPolicyExpansion interface{}
