// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Authors of KubeDig

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/zfz-725/KubeDig/pkg/KubeDigController/api/security.kubedig.com/v1"
	scheme "github.com/zfz-725/KubeDig/pkg/KubeDigController/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KubeDigHostPoliciesGetter has a method to return a KubeDigHostPolicyInterface.
// A group's client should implement this interface.
type KubeDigHostPoliciesGetter interface {
	KubeDigHostPolicies() KubeDigHostPolicyInterface
}

// KubeDigHostPolicyInterface has methods to work with KubeDigHostPolicy resources.
type KubeDigHostPolicyInterface interface {
	Create(ctx context.Context, kubeDigHostPolicy *v1.KubeDigHostPolicy, opts metav1.CreateOptions) (*v1.KubeDigHostPolicy, error)
	Update(ctx context.Context, kubeDigHostPolicy *v1.KubeDigHostPolicy, opts metav1.UpdateOptions) (*v1.KubeDigHostPolicy, error)
	UpdateStatus(ctx context.Context, kubeDigHostPolicy *v1.KubeDigHostPolicy, opts metav1.UpdateOptions) (*v1.KubeDigHostPolicy, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.KubeDigHostPolicy, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.KubeDigHostPolicyList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.KubeDigHostPolicy, err error)
	KubeDigHostPolicyExpansion
}

// kubeDigHostPolicies implements KubeDigHostPolicyInterface
type kubeDigHostPolicies struct {
	client rest.Interface
}

// newKubeDigHostPolicies returns a KubeDigHostPolicies
func newKubeDigHostPolicies(c *SecurityV1Client) *kubeDigHostPolicies {
	return &kubeDigHostPolicies{
		client: c.RESTClient(),
	}
}

// Get takes name of the kubeDigHostPolicy, and returns the corresponding kubeDigHostPolicy object, and an error if there is any.
func (c *kubeDigHostPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.KubeDigHostPolicy, err error) {
	result = &v1.KubeDigHostPolicy{}
	err = c.client.Get().
		Resource("kubedighostpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KubeDigHostPolicies that match those selectors.
func (c *kubeDigHostPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.KubeDigHostPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.KubeDigHostPolicyList{}
	err = c.client.Get().
		Resource("kubedighostpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kubeDigHostPolicies.
func (c *kubeDigHostPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("kubedighostpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kubeDigHostPolicy and creates it.  Returns the server's representation of the kubeDigHostPolicy, and an error, if there is any.
func (c *kubeDigHostPolicies) Create(ctx context.Context, kubeDigHostPolicy *v1.KubeDigHostPolicy, opts metav1.CreateOptions) (result *v1.KubeDigHostPolicy, err error) {
	result = &v1.KubeDigHostPolicy{}
	err = c.client.Post().
		Resource("kubedighostpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kubeDigHostPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kubeDigHostPolicy and updates it. Returns the server's representation of the kubeDigHostPolicy, and an error, if there is any.
func (c *kubeDigHostPolicies) Update(ctx context.Context, kubeDigHostPolicy *v1.KubeDigHostPolicy, opts metav1.UpdateOptions) (result *v1.KubeDigHostPolicy, err error) {
	result = &v1.KubeDigHostPolicy{}
	err = c.client.Put().
		Resource("kubedighostpolicies").
		Name(kubeDigHostPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kubeDigHostPolicy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *kubeDigHostPolicies) UpdateStatus(ctx context.Context, kubeDigHostPolicy *v1.KubeDigHostPolicy, opts metav1.UpdateOptions) (result *v1.KubeDigHostPolicy, err error) {
	result = &v1.KubeDigHostPolicy{}
	err = c.client.Put().
		Resource("kubedighostpolicies").
		Name(kubeDigHostPolicy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kubeDigHostPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kubeDigHostPolicy and deletes it. Returns an error if one occurs.
func (c *kubeDigHostPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("kubedighostpolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kubeDigHostPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("kubedighostpolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kubeDigHostPolicy.
func (c *kubeDigHostPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.KubeDigHostPolicy, err error) {
	result = &v1.KubeDigHostPolicy{}
	err = c.client.Patch(pt).
		Resource("kubedighostpolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
