// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Authors of KubeDig

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/zfz-725/KubeDig/pkg/KubeDigController/api/security.kubedig.com/v1"
	scheme "github.com/zfz-725/KubeDig/pkg/KubeDigController/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KubeDigClusterPoliciesGetter has a method to return a KubeDigClusterPolicyInterface.
// A group's client should implement this interface.
type KubeDigClusterPoliciesGetter interface {
	KubeDigClusterPolicies() KubeDigClusterPolicyInterface
}

// KubeDigClusterPolicyInterface has methods to work with KubeDigClusterPolicy resources.
type KubeDigClusterPolicyInterface interface {
	Create(ctx context.Context, kubeDigClusterPolicy *v1.KubeDigClusterPolicy, opts metav1.CreateOptions) (*v1.KubeDigClusterPolicy, error)
	Update(ctx context.Context, kubeDigClusterPolicy *v1.KubeDigClusterPolicy, opts metav1.UpdateOptions) (*v1.KubeDigClusterPolicy, error)
	UpdateStatus(ctx context.Context, kubeDigClusterPolicy *v1.KubeDigClusterPolicy, opts metav1.UpdateOptions) (*v1.KubeDigClusterPolicy, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.KubeDigClusterPolicy, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.KubeDigClusterPolicyList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.KubeDigClusterPolicy, err error)
	KubeDigClusterPolicyExpansion
}

// kubeDigClusterPolicies implements KubeDigClusterPolicyInterface
type kubeDigClusterPolicies struct {
	client rest.Interface
}

// newKubeDigClusterPolicies returns a KubeDigClusterPolicies
func newKubeDigClusterPolicies(c *SecurityV1Client) *kubeDigClusterPolicies {
	return &kubeDigClusterPolicies{
		client: c.RESTClient(),
	}
}

// Get takes name of the kubeDigClusterPolicy, and returns the corresponding kubeDigClusterPolicy object, and an error if there is any.
func (c *kubeDigClusterPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.KubeDigClusterPolicy, err error) {
	result = &v1.KubeDigClusterPolicy{}
	err = c.client.Get().
		Resource("kubedigclusterpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KubeDigClusterPolicies that match those selectors.
func (c *kubeDigClusterPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.KubeDigClusterPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.KubeDigClusterPolicyList{}
	err = c.client.Get().
		Resource("kubedigclusterpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kubeDigClusterPolicies.
func (c *kubeDigClusterPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("kubedigclusterpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kubeDigClusterPolicy and creates it.  Returns the server's representation of the kubeDigClusterPolicy, and an error, if there is any.
func (c *kubeDigClusterPolicies) Create(ctx context.Context, kubeDigClusterPolicy *v1.KubeDigClusterPolicy, opts metav1.CreateOptions) (result *v1.KubeDigClusterPolicy, err error) {
	result = &v1.KubeDigClusterPolicy{}
	err = c.client.Post().
		Resource("kubedigclusterpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kubeDigClusterPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kubeDigClusterPolicy and updates it. Returns the server's representation of the kubeDigClusterPolicy, and an error, if there is any.
func (c *kubeDigClusterPolicies) Update(ctx context.Context, kubeDigClusterPolicy *v1.KubeDigClusterPolicy, opts metav1.UpdateOptions) (result *v1.KubeDigClusterPolicy, err error) {
	result = &v1.KubeDigClusterPolicy{}
	err = c.client.Put().
		Resource("kubedigclusterpolicies").
		Name(kubeDigClusterPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kubeDigClusterPolicy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *kubeDigClusterPolicies) UpdateStatus(ctx context.Context, kubeDigClusterPolicy *v1.KubeDigClusterPolicy, opts metav1.UpdateOptions) (result *v1.KubeDigClusterPolicy, err error) {
	result = &v1.KubeDigClusterPolicy{}
	err = c.client.Put().
		Resource("kubedigclusterpolicies").
		Name(kubeDigClusterPolicy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kubeDigClusterPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kubeDigClusterPolicy and deletes it. Returns an error if one occurs.
func (c *kubeDigClusterPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("kubedigclusterpolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kubeDigClusterPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("kubedigclusterpolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kubeDigClusterPolicy.
func (c *kubeDigClusterPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.KubeDigClusterPolicy, err error) {
	result = &v1.KubeDigClusterPolicy{}
	err = c.client.Patch(pt).
		Resource("kubedigclusterpolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
