// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Authors of KubeDig

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/zfz-725/KubeDig/pkg/KubeDigController/api/security.kubedig.com/v1"
	scheme "github.com/zfz-725/KubeDig/pkg/KubeDigController/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KubeDigPoliciesGetter has a method to return a KubeDigPolicyInterface.
// A group's client should implement this interface.
type KubeDigPoliciesGetter interface {
	KubeDigPolicies(namespace string) KubeDigPolicyInterface
}

// KubeDigPolicyInterface has methods to work with KubeDigPolicy resources.
type KubeDigPolicyInterface interface {
	Create(ctx context.Context, kubeDigPolicy *v1.KubeDigPolicy, opts metav1.CreateOptions) (*v1.KubeDigPolicy, error)
	Update(ctx context.Context, kubeDigPolicy *v1.KubeDigPolicy, opts metav1.UpdateOptions) (*v1.KubeDigPolicy, error)
	UpdateStatus(ctx context.Context, kubeDigPolicy *v1.KubeDigPolicy, opts metav1.UpdateOptions) (*v1.KubeDigPolicy, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.KubeDigPolicy, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.KubeDigPolicyList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.KubeDigPolicy, err error)
	KubeDigPolicyExpansion
}

// kubeDigPolicies implements KubeDigPolicyInterface
type kubeDigPolicies struct {
	client rest.Interface
	ns     string
}

// newKubeDigPolicies returns a KubeDigPolicies
func newKubeDigPolicies(c *SecurityV1Client, namespace string) *kubeDigPolicies {
	return &kubeDigPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kubeDigPolicy, and returns the corresponding kubeDigPolicy object, and an error if there is any.
func (c *kubeDigPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.KubeDigPolicy, err error) {
	result = &v1.KubeDigPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kubedigpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KubeDigPolicies that match those selectors.
func (c *kubeDigPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.KubeDigPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.KubeDigPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kubedigpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kubeDigPolicies.
func (c *kubeDigPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kubedigpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kubeDigPolicy and creates it.  Returns the server's representation of the kubeDigPolicy, and an error, if there is any.
func (c *kubeDigPolicies) Create(ctx context.Context, kubeDigPolicy *v1.KubeDigPolicy, opts metav1.CreateOptions) (result *v1.KubeDigPolicy, err error) {
	result = &v1.KubeDigPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kubedigpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kubeDigPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kubeDigPolicy and updates it. Returns the server's representation of the kubeDigPolicy, and an error, if there is any.
func (c *kubeDigPolicies) Update(ctx context.Context, kubeDigPolicy *v1.KubeDigPolicy, opts metav1.UpdateOptions) (result *v1.KubeDigPolicy, err error) {
	result = &v1.KubeDigPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kubedigpolicies").
		Name(kubeDigPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kubeDigPolicy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *kubeDigPolicies) UpdateStatus(ctx context.Context, kubeDigPolicy *v1.KubeDigPolicy, opts metav1.UpdateOptions) (result *v1.KubeDigPolicy, err error) {
	result = &v1.KubeDigPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kubedigpolicies").
		Name(kubeDigPolicy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kubeDigPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kubeDigPolicy and deletes it. Returns an error if one occurs.
func (c *kubeDigPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kubedigpolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kubeDigPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kubedigpolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kubeDigPolicy.
func (c *kubeDigPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.KubeDigPolicy, err error) {
	result = &v1.KubeDigPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kubedigpolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
