---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.kubedigOperator.name }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  verbs:
  - get
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - list
  - get
  - create
  - delete
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create
  - update
- apiGroups:
  - batch
  verbs:
  - get
  - create
  - delete
  resources:
  - jobs
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - get  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.kubedigOperator.name }}-manage-controller-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.kubedigOperator.name }}-manage-snitch-job-role
  namespace: {{ .Release.Namespace }}
rules:
# to handle snitch mounts dynamically  
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list  
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - create
  - delete  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.kubedigOperator.name }}-tls-secrets-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - update
  - delete
  resourceNames:
  - {{ .Values.tlsSecrets.kubedigCa }}
  - {{ .Values.tlsSecrets.kubedigClient }}
  - {{ .Values.tlsSecrets.relayServer }}
  - {{ .Values.tlsSecrets.controllerWebhook }}
# cannot restric create by resource name, https://kubernetes.io/docs/reference/access-authn-authz/rbac/  
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create