// SPDX-License-Identifier: Apache-2.0
// Copyright 2023 Authors of KubeDig

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/zfz-725/KubeDig/pkg/KubeDigOperator/client/clientset/versioned/typed/operator.kubedig.com/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeOperatorV1 struct {
	*testing.Fake
}

func (c *FakeOperatorV1) KubeDigConfigs(namespace string) v1.KubeDigConfigInterface {
	return &FakeKubeDigConfigs{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeOperatorV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
