// SPDX-License-Identifier: Apache-2.0
// Copyright 2023 Authors of KubeDig

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	operatorkubedigcomv1 "github.com/zfz-725/KubeDig/pkg/KubeDigOperator/api/operator.kubedig.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKubeDigConfigs implements KubeDigConfigInterface
type FakeKubeDigConfigs struct {
	Fake *FakeOperatorV1
	ns   string
}

var kubedigconfigsResource = schema.GroupVersionResource{Group: "operator.kubedig.com", Version: "v1", Resource: "kubedigconfigs"}

var kubedigconfigsKind = schema.GroupVersionKind{Group: "operator.kubedig.com", Version: "v1", Kind: "KubeDigConfig"}

// Get takes name of the kubeDigConfig, and returns the corresponding kubeDigConfig object, and an error if there is any.
func (c *FakeKubeDigConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *operatorkubedigcomv1.KubeDigConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kubedigconfigsResource, c.ns, name), &operatorkubedigcomv1.KubeDigConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorkubedigcomv1.KubeDigConfig), err
}

// List takes label and field selectors, and returns the list of KubeDigConfigs that match those selectors.
func (c *FakeKubeDigConfigs) List(ctx context.Context, opts v1.ListOptions) (result *operatorkubedigcomv1.KubeDigConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kubedigconfigsResource, kubedigconfigsKind, c.ns, opts), &operatorkubedigcomv1.KubeDigConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &operatorkubedigcomv1.KubeDigConfigList{ListMeta: obj.(*operatorkubedigcomv1.KubeDigConfigList).ListMeta}
	for _, item := range obj.(*operatorkubedigcomv1.KubeDigConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kubeDigConfigs.
func (c *FakeKubeDigConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kubedigconfigsResource, c.ns, opts))

}

// Create takes the representation of a kubeDigConfig and creates it.  Returns the server's representation of the kubeDigConfig, and an error, if there is any.
func (c *FakeKubeDigConfigs) Create(ctx context.Context, kubeDigConfig *operatorkubedigcomv1.KubeDigConfig, opts v1.CreateOptions) (result *operatorkubedigcomv1.KubeDigConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kubedigconfigsResource, c.ns, kubeDigConfig), &operatorkubedigcomv1.KubeDigConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorkubedigcomv1.KubeDigConfig), err
}

// Update takes the representation of a kubeDigConfig and updates it. Returns the server's representation of the kubeDigConfig, and an error, if there is any.
func (c *FakeKubeDigConfigs) Update(ctx context.Context, kubeDigConfig *operatorkubedigcomv1.KubeDigConfig, opts v1.UpdateOptions) (result *operatorkubedigcomv1.KubeDigConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kubedigconfigsResource, c.ns, kubeDigConfig), &operatorkubedigcomv1.KubeDigConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorkubedigcomv1.KubeDigConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKubeDigConfigs) UpdateStatus(ctx context.Context, kubeDigConfig *operatorkubedigcomv1.KubeDigConfig, opts v1.UpdateOptions) (*operatorkubedigcomv1.KubeDigConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kubedigconfigsResource, "status", c.ns, kubeDigConfig), &operatorkubedigcomv1.KubeDigConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorkubedigcomv1.KubeDigConfig), err
}

// Delete takes name of the kubeDigConfig and deletes it. Returns an error if one occurs.
func (c *FakeKubeDigConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kubedigconfigsResource, c.ns, name), &operatorkubedigcomv1.KubeDigConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKubeDigConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kubedigconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &operatorkubedigcomv1.KubeDigConfigList{})
	return err
}

// Patch applies the patch and returns the patched kubeDigConfig.
func (c *FakeKubeDigConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *operatorkubedigcomv1.KubeDigConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kubedigconfigsResource, c.ns, name, pt, data, subresources...), &operatorkubedigcomv1.KubeDigConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorkubedigcomv1.KubeDigConfig), err
}
