# permissions for end users to view kubedighostpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubedighostpolicy-viewer-role
rules:
- apiGroups:
  - security.kubedig.com
  resources:
  - kubedighostpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.kubedig.com
  resources:
  - kubedighostpolicies/status
  verbs:
  - get
