name: ci-test-operator

on:
  push:
    branches:
      - "main"
    paths:
      - "pkg/**"
      - "deployments/get/**"
      - "KubeDig/utils/**"
  pull_request:
    branches:
      - "main"
    paths:
      # test on dep or helm changes
      - "pkg/**"
      - "deployments/**"
      - "KubeDig/utils/**"

# Declare default permissions as read only.
permissions: read-all

jobs:
  kubedig-operator-test:
    name: Build KubeDig Operator
    defaults:
      run:
        working-directory: ./pkg/KubeDigOperator
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          # working-directory only takes effect for "run"
          go-version-file: 'KubeDig/go.mod'

      - name: Build kubedig operator
        run: make docker-build TAG=latest
