name: ci-test-systemd

on:
  push:
    branches: [main]
    paths:
      - "KubeDig/**"
      - "tests/**"
      - "protobuf/**"
      - ".github/workflows/ci-test-systemd.yml"
  pull_request:
    branches: [main]
    paths:
      - "KubeDig/**"
      - "tests/**"
      - "protobuf/**"
      - ".github/workflows/ci-test-systemd.yml"

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    name: Test KubeDig in Systemd Mode
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'KubeDig/go.mod'

      - name: Install the latest LLVM toolchain
        run: ./.github/workflows/install-llvm.sh

      - name: Compile libbpf
        run: ./.github/workflows/install-libbpf.sh

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true
          version: v1.25.0

      - name: Build Systemd Release
        run: make local-release
        working-directory: KubeDig

      - name: Install KubeDig
        run: sudo apt install -y ./dist/kubedig*amd64.deb
        working-directory: KubeDig

      - name: Check journalctl
        run: sudo journalctl -u kubedig --no-pager
      
      - name: Test kubedig using ginkgo 
        run: |
          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
          make
        working-directory: ./tests/nonk8s_env
        timeout-minutes: 30
        
      
